apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stocktraders.ceh
spec:
  group: ceh
  names:
    kind: StockTrader
    listKind: StockTraderList
    plural: stocktraders
    singular: stocktrader
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
