# permissions for end users to view stocktraders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stocktrader-viewer-role
rules:
- apiGroups:
  - operators.ibm.com
  resources:
  - stocktraders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.ibm.com
  resources:
  - stocktraders/status
  verbs:
  - get
