# permissions for end users to view stocktraders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stocktrader-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stocktrader-operator
    app.kubernetes.io/part-of: stocktrader-operator
    app.kubernetes.io/managed-by: kustomize
  name: stocktrader-viewer-role
rules:
- apiGroups:
  - operators.ibm.com
  resources:
  - stocktraders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.ibm.com
  resources:
  - stocktraders/status
  verbs:
  - get
