apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocktrader
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stocktrader
  template:
    metadata:
      labels:
        name: stocktrader
    spec:
      serviceAccountName: stocktrader
      containers:
        - name: stocktrader
          # Replace this with the built image name
          image: ibmstocktrader/stocktrader-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "stocktrader"
