apiVersion: operators.ibm.com/v1
kind: StockTrader
metadata:
  name: example-stocktrader
spec:
  # Default values copied from <project_dir>/helm-charts/stocktrader/values.yaml
  
  database:
    kind: db2
    db: trader
    host: db2trader1-ibm-db2oltp-dev
    id: db2inst1
    password: db2inst1
    port: 50000
  global:
    autoscale: false
    healthCheck: true
    ingress: true
    jsonLogging: false
    monitoring: true
    replicas: 1
  ingress:
    address: <your proxy node IP>:443
  jwt:
    audience: stock-trader
    issuer: http://stock-trader.ibm.com
  kafka:
    address: <your Kafka proxy service>:30000
    apiKey: <your API key>
    topic: stocktrader
    user: token
  looper:
    enabled: false
    image:
      repository: ibmstocktrader/looper
      tag: latest
    url: http://{{ .Release.Name }}-looper-service:9080/looper
  messaging:
    enabled: false
    image:
      repository: ibmstocktrader/messaging
      tag: latest
    notification:
      url: http://{{ .Release.Name }}-notification-service:9080/notification
  mongo:
    authDB: <your Mongo auth database>
    database: <your Mongo database>
    ip: <your Mongo IP>
    password: <your Mongo password>
    port: 27017
    user: <your Mongo user>
  mq:
    channel: DEV.APP.SVRCONN
    host: mqtrader1-mqtrader1
    id: app
    password: pwd
    port: 1414
    queue: NotificationQ
    queueManager: stocktrader
  notificationSlack:
    enabled: false
    image:
      repository: ibmstocktrader/notification-slack
      tag: latest
  notificationTwitter:
    enabled: false
    image:
      repository: ibmstocktrader/notification-twitter
      tag: latest
  odm:
    id: odmAdmin
    password: odmAdmin
    url: http://odmtrader1-ibm-odm-dev:9060/DecisionService/rest/ICP_Trader_Dev_1/determineLoyalty
  oidc:
    auth: https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/authorize
    clientId: <your client id>
    clientSecret: <your client secret>
    issuer: https://idaas.iam.ibm.com
    key: blueidprod
    name: IBMid
    nodePort: <your ingress URL>
    token: https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/token
  openwhisk:
    id: <your id>
    password: <your password>
    url: https://openwhisk.ng.bluemix.net/api/v1/namespaces/jalcorn%40us.ibm.com_dev/actions/PostLoyaltyLevelToSlack
  portfolio:
    image:
      repository: ibmstocktrader/portfolio
      tag: latest
    url: http://{{ .Release.Name }}-portfolio-service:9080/portfolio
  redis:
    cacheInterval: 60
    urlWithCredentials: redis://<your credentials>@redistrader1-ibm-redis-ha-dev-master-svc:6379
  stockQuote:
    apiConnect: https://api.us.apiconnect.ibmcloud.com/jalcornusibmcom-dev/sb/stocks
    iexApiKey: <your IEX API key>
    iexTrading: https://cloud.iexapis.com/stable/stock
    image:
      repository: ibmstocktrader/stock-quote
      tag: latest
    url: http://{{ .Release.Name }}-stock-quote-service:9080/stock-quote
  tradeHistory:
    enabled: false
    image:
      repository: ibmstocktrader/trade-history
      tag: latest
    url: http://{{ .Release.Name }}-trade-history-service:9080/trade-history
  trader:
    enabled: true
    image:
      repository: ibmstocktrader/trader
      tag: basicregistry
  tradr:
    enabled: false
    image:
      repository: ibmstocktrader/tradr
      tag: latest
  twitter:
    accessToken: <your access token>
    accessTokenSecret: <your access token secret>
    consumerKey: <your consumer key>
    consumerSecret: <your consumer secret>
  watson:
    id: apikey
    passwordOrApiKey: <your API key>
    url: https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2017-09-21&sentences=false
  
